import { Inter } from 'next/font/google'
import './globals.css'
import { Footer, Navbar } from '@/components'
import { ContextProvider } from '@/contexts/ContextsProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'San Francisco City Academy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <link rel="icon" href="https://i.ibb.co/cFYDXTW/Screenshot-54-removebg-preview.png" />


      <body className={inter.className}>
      <ContextProvider>

       <Navbar/>

       {children}
      
       <Footer/>
      
      </ContextProvider>
      </body>
    
    </html>
  )
}
